#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @description release valve
# @import github.com/escapace/stack-tools/release/npmCommit

main ()
{
    verbose true
    strict true

    _ npmCommit "${1}" "$2"
}
